border_width = 2
margin = [4, 4]
default_border_color = "#060A13"
floating_border_color = "#EBA628"
focused_border_color = "#f3c3af"


col1 = "#6F3138"
col2 = "#0C2D45"
col3 = "#5A424A"
col4 = "#9D2C32"
col5 = "#D54540"
col6 = "#EBA628"
col7 = "#f3c3af"
col8 = "#aa887a"
col9 = "#6F3138"
col10 = "#0C2D45"
col11 = "#5A424A"
col12 = "#9D2C32"
col13 = "#D54540"
col14 = "#EBA628"
col15 = "#f3c3af"



background = "#060A13"
foreground = "#f3c3af"
