border_width = 2
margin = [4, 4]
default_border_color = "#081315"
floating_border_color = "#C5CFD1"
focused_border_color = "#e5e7e8"


col1 = "#788BA0"
col2 = "#879BB3"
col3 = "#96A5B3"
col4 = "#B5BEC2"
col5 = "#B9C1C4"
col6 = "#C5CFD1"
col7 = "#e5e7e8"
col8 = "#a0a1a2"
col9 = "#788BA0"
col10 = "#879BB3"
col11 = "#96A5B3"
col12 = "#B5BEC2"
col13 = "#B9C1C4"
col14 = "#C5CFD1"
col15 = "#e5e7e8"



background = "#081315"
foreground = "#e5e7e8"
