border_width = 2
margin = [4, 4]
default_border_color = "#252527"
floating_border_color = "#DD6888"
focused_border_color = "#e8b1ba"


col1 = "#E8AD72"
col2 = "#D73998"
col3 = "#B74284"
col4 = "#DA5190"
col5 = "#E35593"
col6 = "#DD6888"
col7 = "#e8b1ba"
col8 = "#a27b82"
col9 = "#E8AD72"
col10 = "#D73998"
col11 = "#B74284"
col12 = "#DA5190"
col13 = "#E35593"
col14 = "#DD6888"
col15 = "#e8b1ba"



background = "#252527"
foreground = "#e8b1ba"
