border_width = 2
margin = [4, 4]
default_border_color = "#0f0f10"
floating_border_color = "#F6BE88"
focused_border_color = "#dfdfe0"


col1 = "#F9A557"
col2 = "#ABC759"
col3 = "#7D7D81"
col4 = "#8E8E92"
col5 = "#A7A7A9"
col6 = "#F6BE88"
col7 = "#dfdfe0"
col8 = "#9c9c9c"
col9 = "#F9A557"
col10 = "#ABC759"
col11 = "#7D7D81"
col12 = "#8E8E92"
col13 = "#A7A7A9"
col14 = "#F6BE88"
col15 = "#dfdfe0"



background = "#0f0f10"
foreground = "#dfdfe0"
