border_width = 2
margin = [4, 4]
default_border_color = "#101011"
floating_border_color = "#D3B1AB"
focused_border_color = "#dfdfdf"


col1 = "#A22810"
col2 = "#A63823"
col3 = "#AE5747"
col4 = "#99827E"
col5 = "#9C9C9C"
col6 = "#D3B1AB"
col7 = "#dfdfdf"
col8 = "#9c9c9c"
col9 = "#A22810"
col10 = "#A63823"
col11 = "#AE5747"
col12 = "#99827E"
col13 = "#9C9C9C"
col14 = "#D3B1AB"
col15 = "#dfdfdf"



background = "#101011"
foreground = "#dfdfdf"
