border_width = 2
margin = [4, 4]
default_border_color = "#161920"
floating_border_color = "#EACB8B"
focused_border_color = "#bfd5d8"


col1 = "#92758E"
col2 = "#98B59F"
col3 = "#A3BD8D"
col4 = "#B38EAD"
col5 = "#D4C186"
col6 = "#EACB8B"
col7 = "#bfd5d8"
col8 = "#859597"
col9 = "#92758E"
col10 = "#98B59F"
col11 = "#A3BD8D"
col12 = "#B38EAD"
col13 = "#D4C186"
col14 = "#EACB8B"
col15 = "#bfd5d8"



background = "#161920"
foreground = "#bfd5d8"
