border_width = 2
margin = [4, 4]
default_border_color = "#141815"
floating_border_color = "#9CC9DD"
focused_border_color = "#e0e0df"


col1 = "#6AA289"
col2 = "#73D3A3"
col3 = "#A59D9E"
col4 = "#D4A79D"
col5 = "#ECDDAE"
col6 = "#9CC9DD"
col7 = "#e0e0df"
col8 = "#9c9c9c"
col9 = "#6AA289"
col10 = "#73D3A3"
col11 = "#A59D9E"
col12 = "#D4A79D"
col13 = "#ECDDAE"
col14 = "#9CC9DD"
col15 = "#e0e0df"



background = "#141815"
foreground = "#e0e0df"
